### ISSUE TITLE
Syntax highlighting error after using a where block

### ISSUE THREAD

**Issue by jaredrhall** [carymrobbins/intellij-haskforce#107]
Using a `where` block appears to break syntax highlighting for code comments following the `where` block:
![screenshot from 2014-12-28 21 18 57](https://cloud.githubusercontent.com/assets/9145692/5565943/4bfe521c-8ed7-11e4-9aab-c65679f24138.png)

**Comment by carymrobbins** [comment]
This seems strange.  I wasn't able to produce it on Mac.  However, it seemed like I was able to reproduce it temporarily on Debian with XMonad.  When I first typed a comment in a blank module, I got erroneous syntax highlighting like your screenshot.  However, upon editing the file further it seemed to go away.  I haven't been able to reproduce it since.

@jaredrhall - Does this happen consistently?  Or does it seem to be temporary?

**Comment by jaredrhall** [comment]
@carymrobbins, Sorry for my delay - I've been away for a few days.

Reproducing it today seemed to be a bit tricky. I created a new file and attempted to just insert the code I had that included the where block. When I attempted to make a comment after the where block, highlighting worked properly. I removed the comment, and then placed a comment before the code. This time, when I went to make the comment after the where block, syntax highlighting broke down. I have attempted removing both the before and after comments and then retyping the after comment, and highlighting still doesn't catch the comment.

**Comment by tolysz** [comment]
I have something and it has `syntaxhighlighting` in it:

    Negative start offset: (-1,772);
    java.lang.Throwable
            at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
            at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:212)
            at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:204)
            at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:200)
            at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
            at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
            at com.intellij.openapi.util.TextRange.create(TextRange.java:136)
            at com.haskforce.highlighting.annotation.external.HLint$Problem.createAnnotation(HLint.java:203)
            at com.haskforce.highlighting.annotation.external.HLint$Problem.createDefaultAnnotations(HLint.java:236)
            at com.haskforce.highlighting.annotation.external.HLint$Problem.createAnnotations(HLint.java:217)
            at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.createAnnotations(HaskellExternalAnnotator.java:102)
            at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.apply(HaskellExternalAnnotator.java:93)
            at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.apply(HaskellExternalAnnotator.java:89)
            at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.apply(HaskellExternalAnnotator.java:28)
            at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:166)
            at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:43)
            at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1$1.run(ExternalToolPass.java:130)
            at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
            at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:124)
            at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
            at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
            at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
            at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
            at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
            at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
            at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
            at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
            at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
            at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
            at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
            at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
            at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
            at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
            at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
            at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
            at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
            at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by carymrobbins** [comment]
@tolysz - That looks like a bug from HLint attempting to use an invalid text range.  I'll log it as a separate bug.

**Comment by carymrobbins** [comment]
@jaredrhall - This is pretty old and I haven't heard any complaints since (nor have I seen it myself) so I'll go ahead and close it for now.  If this still persists with the latest versions of IntelliJ and HaskForce, please reopen this issue.
