### ISSUE TITLE
HLint attempts to use a negative offset

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#121]
From @tolysz, seems we have an issue with HLint using a bad offset when applying an annotation (originally reported in #107).

```
Negative start offset: (-1,772);
java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
        at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:212)
        at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:204)
        at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:200)
        at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
        at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
        at com.intellij.openapi.util.TextRange.create(TextRange.java:136)
        at com.haskforce.highlighting.annotation.external.HLint$Problem.createAnnotation(HLint.java:203)
        at com.haskforce.highlighting.annotation.external.HLint$Problem.createDefaultAnnotations(HLint.java:236)
        at com.haskforce.highlighting.annotation.external.HLint$Problem.createAnnotations(HLint.java:217)
        at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.createAnnotations(HaskellExternalAnnotator.java:102)
        at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.apply(HaskellExternalAnnotator.java:93)
        at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.apply(HaskellExternalAnnotator.java:89)
        at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.apply(HaskellExternalAnnotator.java:28)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:166)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:43)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1$1.run(ExternalToolPass.java:130)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:124)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
        at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
        at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by carymrobbins** [comment]
This will be resolved in version **v0.3-beta.21**
