### ISSUE TITLE
Can't create new project. IntelliJ throws exception.

### ISSUE THREAD

**Issue by kallus** [carymrobbins/intellij-haskforce#205]
At the end of the wizard for creating a new Haskell project, when I click "Finish" nothing happens. In the terminal where I started IntelliJ I see the following exception (throwed once each time I press "Finish"):

	[ 341139]  ERROR - llij.ide.plugins.PluginManager - null 
	java.security.PrivilegedActionException: java.security.PrivilegedActionException: com.intellij.execution.ExecutionException: cabal: '/usr/lib/ghc/bin/ghc' exited with an error:
	ghc: missing -B<dir> option

	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	
...

	[ 341144]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 15.0.1  Build #IC-143.382.35 
	[ 341144]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_80 
	[ 341144]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
	[ 341144]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
	[ 341144]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
	[ 341144]  ERROR - llij.ide.plugins.PluginManager - Last Action:

**Comment by kallus** [comment]
Solved it. The suggested path to the ghc binary was wrong. I think it pointed to an old ghc.

**Comment by carymrobbins** [comment]
Stuff like this shouldn't happen in the latest release since we no longer call out to cabal during the project wizard.  Closing for now, but feel free to reopen (or submit a new issue) if problems persist.
