### ISSUE TITLE
Can't Edit Specific File - 

### ISSUE THREAD

**Issue by T-Spoon** [carymrobbins/intellij-haskforce#231]
It seems that this particular file gives an IndexOutOfBounds exception when trying to edit it:

Stacktrace
```
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.0.3  Build #IC-139.1117.1 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Last Action:  
2016-01-23 00:29:14,499 [  76253]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.0.3  Build #IC-139.1117.1 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Last Action:  
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - chars sequence.length:1630, start:1630, end:0 
java.lang.IndexOutOfBoundsException: chars sequence.length:1630, start:1630, end:0
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:32)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:216)
	at com.intellij.lang.impl.PsiBuilderImpl.getTokenText(PsiBuilderImpl.java:787)
	at com.intellij.lang.impl.PsiBuilderAdapter.getTokenText(PsiBuilderAdapter.java:96)
	at com.intellij.lang.parser.GeneratedParserUtilBase.reportError(GeneratedParserUtilBase.java:666)
	at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_impl_(GeneratedParserUtilBase.java:532)
	at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_(GeneratedParserUtilBase.java:476)
	at com.haskforce.parser.HaskellParser.parseLight(HaskellParser.java:242)
	at com.haskforce.parser.HaskellParser.parse(HaskellParser.java:18)
	at com.haskforce.psi.HaskellParserWrapper.parse(HaskellParserWrapper.java:78)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:763)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutside(Divider.java:94)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutside(Divider.java:54)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:200)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

File Contents
```
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.0.3  Build #IC-139.1117.1 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Last Action:  
2016-01-23 00:29:14,499 [  76253]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.0.3  Build #IC-139.1117.1 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - Last Action:  
2016-01-23 00:29:14,502 [  76256]  ERROR - aemon.impl.PassExecutorService - chars sequence.length:1630, start:1630, end:0 
java.lang.IndexOutOfBoundsException: chars sequence.length:1630, start:1630, end:0
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:32)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:216)
	at com.intellij.lang.impl.PsiBuilderImpl.getTokenText(PsiBuilderImpl.java:787)
	at com.intellij.lang.impl.PsiBuilderAdapter.getTokenText(PsiBuilderAdapter.java:96)
	at com.intellij.lang.parser.GeneratedParserUtilBase.reportError(GeneratedParserUtilBase.java:666)
	at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_impl_(GeneratedParserUtilBase.java:532)
	at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_(GeneratedParserUtilBase.java:476)
	at com.haskforce.parser.HaskellParser.parseLight(HaskellParser.java:242)
	at com.haskforce.parser.HaskellParser.parse(HaskellParser.java:18)
	at com.haskforce.psi.HaskellParserWrapper.parse(HaskellParserWrapper.java:78)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:763)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutside(Divider.java:94)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutside(Divider.java:54)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:200)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by carymrobbins** [comment]
Odd that it would be resolved by removing the `.idea` directory.  I'll keep this open in case other clues develop.
