### ISSUE TITLE
Exceptions thrown in IntelliJ

### ISSUE THREAD

**Issue by newhoggy** [carymrobbins/intellij-haskforce#232]
OS version: OS X 10.11.3
IDE version: IntelliJ IDEA 15.0.3

```
Index: 0
java.lang.IndexOutOfBoundsException: Index: 0
	at com.intellij.util.containers.ContainerUtilRt$EmptyList.get(ContainerUtilRt.java:308)
	at com.haskforce.psi.references.HaskellReference.multiResolve(HaskellReference.java:99)
	at com.haskforce.psi.references.HaskellReference.resolve(HaskellReference.java:236)
	at org.jetbrains.kotlin.idea.inspections.OldStdlibApiInspection.checkReference(OldStdlibApiInspection.kt:49)
	at org.jetbrains.kotlin.idea.inspections.OldStdlibApiInspection.access$checkReference(OldStdlibApiInspection.kt:29)
	at org.jetbrains.kotlin.idea.inspections.OldStdlibApiInspection$buildVisitor$1.visitElement(OldStdlibApiInspection.kt:38)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.haskforce.psi.impl.HaskellConidImpl.accept(HaskellConidImpl.java:29)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by carymrobbins** [comment]
Related to #164.

I've fixed this in master, it should be available in **0.3-beta.27**.
