### ISSUE TITLE
HaskellToolsConsole should release Editor

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#269]
This happens when closing a Haskell project.

```
Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released:
com.intellij.openapi.util.TraceableDisposable.ObjectNotDisposedException: See stack trace responsible for creation of unreleased object below 
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:145)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:193)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:174)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:63)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:1001)
	at com.intellij.execution.impl.ConsoleViewImpl$15.compute(ConsoleViewImpl.java:942)
	at com.intellij.execution.impl.ConsoleViewImpl$15.compute(ConsoleViewImpl.java:939)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.execution.impl.ConsoleViewImpl.c(ConsoleViewImpl.java:939)
	at com.intellij.execution.impl.ConsoleViewImpl.i(ConsoleViewImpl.java:524)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:503)
	at com.haskforce.ui.tools.ToolConsoleView.com$haskforce$ui$tools$ToolConsoleView$$initUI(HaskellToolsConsole.scala:134)
	at com.haskforce.ui.tools.ToolConsoleView$.create(HaskellToolsConsole.scala:155)
	at com.haskforce.ui.tools.HaskellToolsConsole.com$haskforce$ui$tools$HaskellToolsConsole$$newConsole(HaskellToolsConsole.scala:114)
	at com.haskforce.ui.tools.HaskellToolsConsole$$anonfun$com$haskforce$ui$tools$HaskellToolsConsole$$getConsole$1.apply(HaskellToolsConsole.scala:106)
	at com.haskforce.ui.tools.HaskellToolsConsole$$anonfun$com$haskforce$ui$tools$HaskellToolsConsole$$getConsole$1.apply(HaskellToolsConsole.scala:106)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at com.haskforce.ui.tools.HaskellToolsConsole.com$haskforce$ui$tools$HaskellToolsConsole$$getConsole(HaskellToolsConsole.scala:106)
	at com.haskforce.ui.tools.HaskellToolsConsole$$anonfun$write$1.apply$mcV$sp(HaskellToolsConsole.scala:57)
	at com.haskforce.utils.SAMUtils$$anon$3.run(SAMUtils.scala:18)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by carymrobbins** [comment]
Fixed by commit 3b5aabb314146bb56d72d2d3e64e5d07f56ab9f9
