### ISSUE TITLE
The plugin crashes when I click "Create New Project" or try to import project

### ISSUE THREAD

**Issue by faucct** [carymrobbins/intellij-haskforce#276]
Logs:
```
 Маркер — 28 мая 2016 г., 19:25:20
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - org.jetbrains.haskell.module.HaskellModuleType cannot be cast to com.haskforce.HaskellModuleType 
java.lang.ClassCastException: org.jetbrains.haskell.module.HaskellModuleType cannot be cast to com.haskforce.HaskellModuleType
	at com.haskforce.HaskellModuleType$.getInstance(HaskellModuleType.scala:17)
	at com.haskforce.HaskellModuleBuilder.getModuleType(HaskellModuleBuilder.scala:59)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.getModuleTypeName(ModuleBuilder.java:384)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.getPresentableName(ModuleBuilder.java:380)
	at com.intellij.ide.util.newProjectWizard.TemplatesGroup.<init>(TemplatesGroup.java:61)
	at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:298)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:136)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:50)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:30)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:106)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:277)
	at java.awt.Component.processMouseEvent(Component.java:6414)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
	at java.awt.Component.processEvent(Component.java:6179)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
	at java.awt.Container.dispatchEventImpl(Container.java:2128)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 15.0.6  Build #IC-143.2370.31 
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2016-05-28 20:25:21,398 [ 451797]  ERROR - llij.ide.plugins.PluginManager - Last Action: ViewToolBar 
 ```

**Comment by carymrobbins** [comment]
Do you have multiple Haskell plugins installed?  The `org.jetbrains.haskell.module.HaskellModuleType` class seems to be from a different plugin - [atsky/haskell-idea-plugin](https://github.com/atsky/haskell-idea-plugin/blob/master/plugin/src/org/jetbrains/haskell/module/HaskellModuleType.kt).

**Comment by carymrobbins** [comment]
If you do have other Haskell plugins installed, but sure to uninstall them and restart IntelliJ.

**Comment by faucct** [comment]
Totally. Thanks!
