### ISSUE TITLE
Intention "add type signature" isn't working

### ISSUE THREAD

**Issue by mnn** [carymrobbins/intellij-haskforce#312]
Everything else seems to be fine (code completion, type info, syntax checking). I would appreciate any advice.

```
ghc-mod version 5.6.0.0 compiled by GHC 7.10.3
The Glorious Glasgow Haskell Compilation System, version 7.10.3
IntelliJ IDEA 2016.2.5 Ultimate
Ubuntu 16.04
```

PS: I am a total beginner in Haskell and yet doesn't fully understand many things, like build process. But `stack build` and running executable is working, so I assume I have set it up properly.

**Comment by carymrobbins** [comment]
I'd check out the [Haskell Tools Console](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#haskell-tools-console) for any errors related to external tools.

Can you define "isn't working"? Maybe some steps to reproduce the issue? Also, if you could include your GHC and HaskForce versions that'd be useful.

**Comment by carymrobbins** [comment]
Actually, it's worth noting that the intention relies on GHC warnings and not ghc-mod, so really the Haskell Tools Console wouldn't be useful in this case. Aside from the versions I mentioned, you might want to also report any errors related to HaskForce you can find in the [IntelliJ logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files).

**Comment by mnn** [comment]
By "isn't working" I mean I don't get the yellow squiggly line and even when I alt+enter or invoke "refactor this" on a type-less definition IDEA doesn't offer me it in a menu (I was looking for same behavior as you have shown on your page - http://haskforce.com/images/add-type-sig.gif).

I'll dig into logs later.

**Comment by mnn** [comment]
Alright, I haven't went over whole log from IDEA start, but there is this error repeating a lot of times (not sure if relevant at all):

```
2016-10-29 06:43:16,296 [  23181]  ERROR - plication.impl.ApplicationImpl - Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 4,4,main] 208670784
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.2.5#IU-162.2228.15 IDEA, eap:false, os:Linux 4.4.0-45-generic, java-version:JetBrains s.r.o 1.8.0_112-release-287-b2,6,main] 1116605362 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:943)
	at com.intellij.psi.impl.source.PsiFileImpl.f(PsiFileImpl.java:173)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:824)
	at com.intellij.psi.impl.source.PsiFileImpl.getChildren(PsiFileImpl.java:830)
	at com.haskforce.cabal.query.CabalQuery.getLibrary(CabalQuery.scala:38)
	at com.haskforce.cabal.query.CabalQuery.getBuildInfo(CabalQuery.scala:56)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$1.apply(CabalQuery.scala:65)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$1.apply(CabalQuery.scala:64)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.CabalQuery.findBuildInfoForSourceFile(CabalQuery.scala:64)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$3.apply(CabalQuery.scala:74)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$3.apply(CabalQuery.scala:74)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.CabalQuery.findBuildInfoForSourceFile(CabalQuery.scala:74)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$2.apply(CabalQuery.scala:70)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$2.apply(CabalQuery.scala:70)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.CabalQuery.findBuildInfoForSourceFile(CabalQuery.scala:70)
	at com.haskforce.cabal.query.BuildInfoUtil$$anonfun$getBuildInfo$2.apply(BuildInfoUtil.scala:14)
	at com.haskforce.cabal.query.BuildInfoUtil$$anonfun$getBuildInfo$2.apply(BuildInfoUtil.scala:12)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.BuildInfoUtil$.getBuildInfo(BuildInfoUtil.scala:12)
	at com.haskforce.cabal.query.BuildInfoUtil.getBuildInfo(BuildInfoUtil.scala)
	at com.haskforce.highlighting.annotation.external.HLint.getParamsFromCabal(HLint.java:118)
	at com.haskforce.highlighting.annotation.external.HLint.getParams(HLint.java:113)
	at com.haskforce.highlighting.annotation.external.HLint.access$100(HLint.java:45)
	at com.haskforce.highlighting.annotation.external.HLint$3.apply(HLint.java:91)
	at com.haskforce.highlighting.annotation.external.HLint$3.apply(HLint.java:87)
	at scala.util.Either.fold(Either.scala:99)
	at com.haskforce.highlighting.annotation.external.HLint.parseProblems(HLint.java:80)
	at com.haskforce.highlighting.annotation.external.HLint.lint(HLint.java:58)
	at com.haskforce.highlighting.annotation.external.impl.HLintProblemsProvider.getProblems(HLintProblemsProvider.scala:24)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1$$anonfun$apply$1.apply(HaskellExternalAnnotator.scala:94)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1$$anonfun$apply$1.apply(HaskellExternalAnnotator.scala:94)
	at scala.Option.map(Option.scala:146)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1.apply(HaskellExternalAnnotator.scala:94)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1.apply(HaskellExternalAnnotator.scala:94)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$.buildForFile(HaskellExternalAnnotator.scala:94)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.doAnnotate(HaskellExternalAnnotator.scala:44)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.doAnnotate(HaskellExternalAnnotator.scala:19)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mnn** [comment]
GHC is of version 7.10.3 and Haskforce 0.3-beta.36 (it doesn't offer me an update so I hope it is the most recent released version).

**Comment by carymrobbins** [comment]
I was incorrect before, I've updated my previous comment. Check the Haskell Tools Console to see what's going on. However, regarding your reported stack trace, that might be preventing ghc-mod from being able to annotate the source, so let me fix that bug and I'll cut a release.

**Comment by mnn** [comment]
Here's output from Haskell Tools Console:
```
Using working directory: /home/xxx/workspace/haskell/project
Starting ghc-modi process: /usr/bin/stack exec -- /home/xxx/.cabal/bin/ghc-mod legacy-interactive
check /mnt/somePath/workspace/haskell/project/app/Main.hs
Warning: STACK_EXE set, preferring Stack project

Unable to parse problems from ghc-modi: Warning: STACK_EXE set, preferring Stack project
check /mnt/somePath/workspace/haskell/project/app/Main.hs
<empty message>
Using working directory: /home/xxx/workspace/haskell/project
Starting ghc-modi process: /usr/bin/stack exec -- /home/xxx/.cabal/bin/ghc-mod legacy-interactive
check /mnt/somePath/workspace/haskell/project/app/Main.hs
Warning: STACK_EXE set, preferring Stack project

Unable to parse problems from ghc-modi: Warning: STACK_EXE set, preferring Stack project
check /mnt/somePath/workspace/haskell/project/app/Main.hs
<empty message>
check /mnt/somePath/workspace/haskell/project/app/Main.hs
<empty message>
check /mnt/somePath/workspace/haskell/project/app/Main.hs
<empty message>
```

**Comment by carymrobbins** [comment]
Ok, this seems obvious in retrospect, but since ghc-mod is _not_ reporting a warning for the missing type signature, you may need to explicitly provide the `-fwarn-missing-signatures` flag.  You can do this via a few different methods -

1. Using a `{-# OPTIONS_GHC -fwarn-missing-signatures #-}` pragma at the top of your file.
2. Including `ghc-options: -fwarn-missing-signatures` in your project's cabal file.
3. Adding `-g -fwarn-missing-signatures` to the flags list when configuring ghc-modi in the Haskell Tools settings.

Sorry for the delayed resolution. Let me know if this alleviates the issue.

**Comment by mnn** [comment]
@carymrobbins After adding flags it works nicely, great! Thank you very much.

**Comment by carymrobbins** [comment]
Thanks @mnn! I've updated the Quick Start Guide accordingly; see [Automatically add type signatures](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#automatically-add-type-signatures).
