### ISSUE TITLE
An exception

### ISSUE THREAD

**Issue by batya239** [carymrobbins/intellij-haskforce#327]
ystemEventQueueThread: Thread[AWT-EventQueue-0 2017.2.2#IC-172.3757.5 IDEA, eap:true, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-915-b10,6,main] 848960809

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1076)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:176)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:836)
	at com.intellij.psi.impl.source.PsiFileImpl.getChildren(PsiFileImpl.java:842)
	at com.haskforce.cabal.query.CabalQuery.getLibrary(CabalQuery.scala:38)
	at com.haskforce.cabal.query.CabalQuery.getBuildInfo(CabalQuery.scala:56)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$1.apply(CabalQuery.scala:65)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$1.apply(CabalQuery.scala:64)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.CabalQuery.findBuildInfoForSourceFile(CabalQuery.scala:64)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$3.apply(CabalQuery.scala:74)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$3.apply(CabalQuery.scala:74)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.CabalQuery.findBuildInfoForSourceFile(CabalQuery.scala:74)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$2.apply(CabalQuery.scala:70)
	at com.haskforce.cabal.query.CabalQuery$$anonfun$findBuildInfoForSourceFile$2.apply(CabalQuery.scala:70)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.CabalQuery.findBuildInfoForSourceFile(CabalQuery.scala:70)
	at com.haskforce.cabal.query.BuildInfoUtil$$anonfun$getBuildInfo$2.apply(BuildInfoUtil.scala:14)
	at com.haskforce.cabal.query.BuildInfoUtil$$anonfun$getBuildInfo$2.apply(BuildInfoUtil.scala:12)
	at scala.Option.flatMap(Option.scala:171)
	at com.haskforce.cabal.query.BuildInfoUtil$.getBuildInfo(BuildInfoUtil.scala:12)
	at com.haskforce.cabal.query.BuildInfoUtil.getBuildInfo(BuildInfoUtil.scala)
	at com.haskforce.highlighting.annotation.external.HLint.getParamsFromCabal(HLint.java:118)
	at com.haskforce.highlighting.annotation.external.HLint.getParams(HLint.java:113)
	at com.haskforce.highlighting.annotation.external.HLint.access$100(HLint.java:45)
	at com.haskforce.highlighting.annotation.external.HLint$3.apply(HLint.java:91)
	at com.haskforce.highlighting.annotation.external.HLint$3.apply(HLint.java:87)
	at scala.util.Either.fold(Either.scala:99)
	at com.haskforce.highlighting.annotation.external.HLint.parseProblems(HLint.java:80)
	at com.haskforce.highlighting.annotation.external.HLint.lint(HLint.java:58)
	at com.haskforce.highlighting.annotation.external.impl.HLintProblemsProvider.getProblems(HLintProblemsProvider.scala:24)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1$$anonfun$apply$1.apply(HaskellExternalAnnotator.scala:94)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1$$anonfun$apply$1.apply(HaskellExternalAnnotator.scala:94)
	at scala.Option.map(Option.scala:146)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1.apply(HaskellExternalAnnotator.scala:94)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$$anonfun$buildForFile$1.apply(HaskellExternalAnnotator.scala:94)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$State$.buildForFile(HaskellExternalAnnotator.scala:94)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.doAnnotate(HaskellExternalAnnotator.scala:44)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator.doAnnotate(HaskellExternalAnnotator.scala:19)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by carymrobbins** [comment]
@batya239 - Thanks for the report. This looks related to https://github.com/carymrobbins/intellij-haskforce/issues/288, so follow that issue for details as to its resolution.
