### ISSUE TITLE
Build Project fails

### ISSUE THREAD

**Issue by d3xter** [carymrobbins/intellij-haskforce#342]
I've installed Haskforce 0.39 in Intellij IDEA 2017.2.4,
created a new stack project and configured all Haskell-Tools.

Added a new file *src/Main.hs"
and put the following code in it.

    module Main where

    main :: IO ()
    main = putStrLn "Hello World"

Now when I press the *Build Project*-Button I get:

```Error:Internal error: (java.lang.ClassNotFoundException) scala.Function1
java.lang.ClassNotFoundException: scala.Function1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.haskforce.jps.model.JpsHaskellModelSerializerExtension.getProjectExtensionSerializers(JpsHaskellModelSerializerExtension.java:83)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadFromDirectory(JpsProjectLoader.java:123)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadProject(JpsProjectLoader.java:101)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:41)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:79)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:267)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by carymrobbins** [comment]
@d3xter Seems `scala-library-2.11.8` was bundled with the plugin archive as opposed to `2.11.7`, so the builder class loader isn't able to find it. I'll get this resolved and a snapshot build up for you to test here shortly.

**Comment by carymrobbins** [comment]
@d3xter I've cut a snapshot release that should fix this issue. Let me know if it does or does not work for you.

https://github.com/carymrobbins/intellij-haskforce/releases/tag/v0.3.40-SNAPSHOT-7b63749

**Comment by nachogarrone** [comment]
@carymrobbins it works with that update! thanks

**Comment by carymrobbins** [comment]
Thanks @nachogarrone, I'll go ahead and close the issue.
