### ISSUE TITLE
Failed to build Scala code with SBT

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#421]
```
Error:Internal error: (java.lang.NoClassDefFoundError) Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:135)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by carymrobbins** [comment]
```
Error:Internal error: (java.lang.ClassNotFoundException) com.intellij.execution.ExecutionException
java.lang.ClassNotFoundException: com.intellij.execution.ExecutionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.haskforce.jps.HaskForceBuilder.createModuleLevelBuilders(HaskForceBuilder.java:26)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:56)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:34)
	at org.jetbrains.jps.incremental.BuilderRegistry$Holder.<clinit>(BuilderRegistry.java:37)
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:135)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
