### ISSUE TITLE
Support for IDEA 2021.1

### ISSUE THREAD

**Issue by mouse07410** [carymrobbins/intellij-haskforce#447]
It looks like this plugin cannot work with the current IDEA 2021.1. Immediately after installing it and restarting IDEA, it crashes with
```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.util.concurrent.CompletionException: java.lang.AssertionError
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
    at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
    at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:802)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:383)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:103)
    at com.intellij.ide.b.m.ag.a(ag.java:93)
    at com.intellij.ide.b.m.e.b(e.java:279)
    at com.intellij.ide.b.m.f.b(f.java:276)
    at com.intellij.ide.b.m.f.c(f.java:169)
    at com.intellij.ide.b.m.f.a(f.java:81)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:95)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:310)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:250)
    at com.intellij.ide.plugins.MainRunner.lambda$start$1(MainRunner.java:41)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError
    at com.intellij.ide.plugins.ClassLoaderConfigurator.configure(ClassLoaderConfigurator.java:169)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:1093)
    at com.intellij.ide.plugins.PluginManagerCore.loadAndInitializePlugins(PluginManagerCore.java:1364)
    at com.intellij.ide.plugins.PluginManagerCore.lambda$initPlugins$20(PluginManagerCore.java:803)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
    ... 23 more

-----
Your JRE: 11.0.10+9-b1341.35 x86_64 (JetBrains s.r.o.)
/Users/ur20980/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111/IntelliJ IDEA.app/Contents/jbr/Contents/Home
```

**Comment by carymrobbins** [comment]
The latest release should resolve this - https://github.com/carymrobbins/intellij-haskforce/releases/tag/v0.3.46

Please reopen or submit a new issue if you encounter any other problems!
