### ISSUE TITLE
Fails to build any project with NoClassDefFoundError

### ISSUE THREAD

**Issue by grguthrie** [carymrobbins/intellij-haskforce#448]
I have a new install of IntelliJ Idea 2021.1 (updated) running fine. Then I opened a .hs file and it asked for a haskell plugin - I had HaskForce (disabled) and said yes - enable and update. 
Then restarting the IDE it gives this error: and the IDE cannot even start.
I had to remove the Haskforce plugin to get it to work.
Thanks for any hints.

Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.util.concurrent.CompletionException: java.lang.AssertionError
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
    at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
    at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:802)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:383)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:103)
    at com.intellij.ide.b.m.ag.a(ag.java:93)
    at com.intellij.ide.b.m.e.b(e.java:279)
    at com.intellij.ide.b.m.f.b(f.java:276)
    at com.intellij.ide.b.m.f.c(f.java:169)
    at com.intellij.ide.b.m.f.a(f.java:81)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:95)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:310)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:250)
    at com.intellij.ide.plugins.MainRunner.lambda$start$1(MainRunner.java:41)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError
    at com.intellij.ide.plugins.ClassLoaderConfigurator.configure(ClassLoaderConfigurator.java:169)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:1093)
    at com.intellij.ide.plugins.PluginManagerCore.loadAndInitializePlugins(PluginManagerCore.java:1364)
    at com.intellij.ide.plugins.PluginManagerCore.lambda$initPlugins$20(PluginManagerCore.java:803)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
    ... 23 more

-----
Your JRE: 11.0.10+9-b1341.35 amd64 (JetBrains s.r.o.)
E:\Developer\JetBrains\IntelliJ IDEA 2021.1\jbr

**Comment by mrm-david** [comment]
I have a maybe similar issue with Pycharm 2020.3 : when installing haskforce, after restarting the IDE, it show in the plugin list as not installed.

The installation fails without a message for me.

**Comment by carymrobbins** [comment]
This should be fixed in the latest release - https://github.com/carymrobbins/intellij-haskforce/releases/tag/v0.3.46

Please reopen or submit a new issue if you encounter any other problems!

**Comment by grguthrie** [comment]
Than you.

I reenabled the plugin, and actually downloaded and installed from the website.

***@***.***D75734.F59186B0]

Trying to build simple .hs file I get this:

Internal error (java.lang.NoClassDefFoundError): Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
                at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:32)
                at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:127)
                at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:301)
                at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)
                at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)

And in fact, it breaks all other projects (.java) as well, I had to disable the plugin to get anything to build.

Gregory Guthrie
