### ISSUE TITLE
Show Types on hover

### ISSUE THREAD

**Issue by archaeron** [carymrobbins/intellij-haskforce#90]
t would be really helpful if we could see the type of an expression by just hovering over it.

Example:

```haskell
data Nat =
	  Zero
	| Succ Nat
	deriving Show

natToInteger1 Zero = 0
natToInteger1 (Succ n) = natToInteger1 n + 1
```

It could show a tooltip with something like `n :: Nat` when I hover over `n`.

**Comment by carymrobbins** [comment]
**Update** - Kudos to @KasperJanssens who is currently implementing this with ghc-mod in pull request #105.  It seems to work quite well, so if you are interested you are more than welcome to build and test his branch to see if it works for you.  I'm expecting that it'll get merged pretty soon.  Once that happens, I'll ship a new release for it.

**Comment by carymrobbins** [comment]
The latest release is out and currently ships with this feature!  Thanks again to @KasperJanssens for implementing it.  It currently requires **ghc-mod(i)** and can be triggered by placing the cursor on a name (or highlighting an expression) and pressing `Alt =` on Windows/Linux or `F11` on Mac.  It can be found in the menus under **View > Type Info**.

**Comment by archaeron** [comment]
it seems to work. this is soooo cool!
Thank you very much.
I believe this is great especially for beginners.

**Comment by JorisM** [comment]
@carymrobbins @KasperJanssens 
aaahh thank you so much! this is wonderful news!

**Comment by shockone** [comment]
It raises the following error in IDEA 14.1

```
21:46:50 Throwable
         Access is allowed from event dispatch thread only.
         Details: EventQueue.isDispatchThread()=false
         isDispatchThread()=false
         Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@41f281b5
         Current thread: Thread[ApplicationImpl pooled thread 255,4,main] 591925189
         SystemEventQueueThread: Thread[AWT-EventQueue-1 14.1#IC-140.2493.5, eap:true,6,main] 1970754472
         "AWT-EventQueue-1 14.1#IC-140.2493.5, eap:true" prio=0 tid=0x0 nid=0x0 runnable
         java.lang.Thread.State: RUNNABLE
         (in native)
         at apple.awt.CRenderer.doRect(Native Method)
         at apple.awt.OSXSurfaceData.doRect(OSXSurfaceData.java:1247)
         at apple.awt.CRenderer.fillRect(CRenderer.java:157)
         at apple.awt.CRenderer.fillRect(CRenderer.java:145)
         at sun.java2d.pipe.ValidatePipe.fillRect(ValidatePipe.java:58)
         at sun.java2d.SunGraphics2D.fillRect(SunGraphics2D.java:2505)
         at javax.swing.JLayeredPane.paint(JLayeredPane.java:561)
         at javax.swing.JComponent.paintChildren(JComponent.java:870)
         at javax.swing.JComponent.paint(JComponent.java:104... (show balloon)
```

**Comment by carymrobbins** [comment]
@shockone - I think that issue is currently being tracked in #135.

**Comment by shockone** [comment]
@carymrobbins, sorry, haven't notice that.

**Comment by carymrobbins** [comment]
@shockone - No problem at all!  Thanks for letting me know that you're affected by this issue.

**Comment by kindlychung** [comment]
View -> Type info doesn't do anything here. Ctrl-J does give me a pop up, but only to say that type info is not available. I have all the external tools installed via stack and configured. 

Here is an example file:

```
{-# OPTIONS_GHC -fwarn-missing-signatures #-}

import           Data.Char

factorial :: (Integral a) => a -> a
factorial 0 = 1
factorial n = n * factorial (n - 1)

tell :: (Show a) => [a] -> String
tell []      = "The list is empty"
tell [firstElem]     = "The list has one elem: " ++ show firstElem
tell [firstElem, secondElm]  = "The list has two elems: " ++ show firstElem ++ show secondElm
tell (f:s:_) = "The list is long, first two elems are: " ++ show f ++ show s

capital :: String -> String
capital ""         = "Empty string, oops!"
capital mylist@(myx:_) = "The first letter of " ++ mylist ++ " is " ++ [myx]

bmiTell :: (RealFloat a) => a -> a -> String
bmiTell weight height
  | bmi <= skinny = "Underweight"
  | bmi <= normal = "Normal"
  | bmi <= fat = "Fat"
  | otherwise = "Whale!"
  where bmi = weight / height ** 2.0
        (skinny, normal, fat) = (18.5, 25.0, 30.0)


initials :: String -> String -> String
initials firstName lastName = [toUpper f] ++ ". " ++ [toUpper l] ++ ". " where
  (f:_) = firstName
  (l:_) = lastName

main :: IO()
main = do
  print $ factorial (5 :: Integer)
  print $ tell [1 :: Integer, 2, 3]
  print $ tell [1 :: Integer, 2]
  print $ tell [1 :: Integer]
  print $ tell ([] :: String)
  print $ capital "Dracula"
  print $ capital ""
  print $ bmiTell (55.5 :: Float) 1.60
  print $ initials "kaiyin" "zhong"
```

Place the cursor on `factorial` and press ctrl-j, and you should reproduce the issue.
